### ISSUE TITLE
Error when creating table

### ISSUE THREAD

**Issue by abronte** [cockroachdb/activerecord-cockroachdb-adapter#3] opened 2017-04-06 05:51 UTC
I'm using the latest activerecord-cockroachdb-adapter gem (0.1.1).

This is my table in the migration (generated by devise):
```
  def change
    create_table :users do |t|
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at

      t.boolean :premium, default: false

      t.timestamps null: false
    end

    add_index :users, :email,                unique: true
    add_index :users, :reset_password_token, unique: true
    # add_index :users, :confirmation_token,   unique: true
    # add_index :users, :unlock_token,         unique: true
  end
```

When I try to run the migration I get 
```
PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
```

Heres the full stacktrace:
```
$ rake db:migrate
== 20170406053035 DeviseCreateUsers: migrating ================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  type 'character varying' does not exist
: SELECT 'character varying'::regtype::oid
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
PG::InternalError: ERROR:  type 'character varying' does not exist
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:384:in `lookup_cast_type'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/quoting.rb:110:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:67:in `quote_default_expression'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `quote_default_expression'


/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:113:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:18:in `add_column_options!'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:34:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:11:in `visit_ColumnDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `block in visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `map'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:45:in `visit_TableDefinition'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `create_table'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/Users/adam/Dropbox (Personal)/Projects/myproject/db/migrate/20170406053035_devise_create_users.rb:3:in `change'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/adam/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/adam/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by abronte** [comment] 2017-04-06 06:06
Cockroachdb version:
```
$ cockroach version
Build Tag:    beta-20170309
Build Time:   2017/03/18 02:24:28
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8
C Compiler:   4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
Build SHA-1:  dd3a574da6734faebf523d7cc2df244ab662527d
Build Type:   development
```

**Comment by abronte** [comment] 2017-04-06 06:12
Updated to the latest cockroachdb beta  and still the same issue.

```
Build Tag:    beta-20170330
Build Time:   2017/03/30 15:14:06
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8
C Compiler:   gcc 6.3.0
Build SHA-1:  f0f5783cc67f9cda16cedf1b88ca0691b0b65884
Build Type:   release
```

**Comment by jordanlewis** [comment] 2017-04-06 14:19
Hi @abronte, thanks for the report and for trying out CockroachDB.

The problem is caused by a bug in the gem's handling of the `default: ""` setting on string columns. While we work on fixing this, you can work around this issue by removing the defaults from your string columns.

**Comment by abronte** [comment] 2017-04-06 17:51
Ah good to know. I ended up just executing a raw sql CREATE TABLE in the migration and that seemed to work.

**Comment by joerocklin** [comment] 2017-05-08 02:06
I'm seeing similar problems with boolean and integer types with default values. Is there a general problem with `default` values? I would start looking into how to fix it, but I don't know a lot of details about writing activerecord connectors. If you have some pointers on where to get started I might be able to poke around.

gem pulled from git & cockroachdb version:
```
Build Tag:    v1.0-rc.2
Build Time:   2017/05/06 18:13:32
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.1
C Compiler:   4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
Build SHA-1:  1700211837c3e519bf093f8cda26fe2afb028ff3
Build Type:   development
```

**Comment by jordanlewis** [comment] 2017-05-08 16:27
Yes, default values in general are susceptible to a similar issue as this one. I'm afraid I can't offer too much guidance on how to fix this issue as I'd really have to go digging to fix this from the connector side. You'll need to figure out where defaults are handled in the Postgres connector, which this connector inherits from, and change the behavior by overriding it.

I'm still planning on fixing this kind of issue from the CockroachDB side. It stems from an incompatibility in the names of the types that we export vs the names of types that PostgreSQL exports.

**Comment by jordanlewis** [comment] 2017-06-12 21:08
A fix for this should be coming soon from the CockroachDB side - see https://github.com/cockroachdb/cockroach/issues/16476. Thanks for your patience!

**Closed** 2017-06-12 21:51 UTC
