### ISSUE TITLE
Wrongly schema.rb after alter table

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#200] opened 2021-04-28 13:33 UTC
Hello,

next problem wich we have is that the schema.rb does not reflect the database, when we alter tables.

1.
When I add a default value afterwards with `change_column :my_table, :code, :string, default: ''` then this default value is not in the schema.rb

There is still: `t.string "code"` without any default

**Comment by keithdoggett** [comment] 2021-04-29 15:57
I've seen some issues with default values before, although it was due to parsing errors. I can try to recreate this and see what's causing it.

**Comment by keithdoggett** [comment] 2021-05-12 14:57
I wrote a test for this and tried it in an application using version 6.1 and could not reproduce this. What version was this showing up in?

**Comment by Piioo** [comment] 2021-05-18 12:46
It was in this version: 6.1.0.pre.beta.3

We have this problem in our Project, I will check with a new one.

**Comment by Piioo** [comment] 2021-05-18 13:04
This is my problem, when I add a default value with a change_column then I cant find it in the schema.rb.
But it is in the DB structure. 


This is from a new project:

```diff
diff --git a/db/migrate/20210518125847_add_field.rb b/db/migrate/20210518125847_add_field.rb
index 20ff4f0..2f94af8 100644
--- a/db/migrate/20210518125847_add_field.rb
+++ b/db/migrate/20210518125847_add_field.rb
@@ -1,4 +1,5 @@
 class AddField < ActiveRecord::Migration[6.1]
   def change
+    change_column :users, :name, :string, default: ''
   end
 end
diff --git a/db/schema.rb b/db/schema.rb
index 81d55ee..5a877c9 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -10,7 +10,7 @@
 #
 # It's strongly recommended that you check this file into your version control system.

-ActiveRecord::Schema.define(version: 2021_05_18_125729) do
+ActiveRecord::Schema.define(version: 2021_05_18_125847) do

   create_table "users", force: :cascade do |t|
     t.string "name"
(END)
```

<img width="638" alt="Bildschirmfoto 2021-05-18 um 15 02 18" src="https://user-images.githubusercontent.com/4640423/118655895-46069980-b7ea-11eb-995f-c25a648502fc.png">

**Comment by keithdoggett** [comment] 2021-05-18 15:26
Hmm, that is strange. I just tested it again with the following migrations.

```rb
class CreateUsers < ActiveRecord::Migration[6.1]
  def change
    create_table :users do |t|
      t.string :code
      t.timestamps
    end
  end
end
```

```rb
class AddDefaultToUserCode < ActiveRecord::Migration[6.1]
  def change
    change_column :users, :code, :string, default: ''
  end
end
```

I ran `rake db:migrate` after each of these and at first observed `schema.rb` as

```rb
  create_table "users", force: :cascade do |t|
    t.string "code"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

then after the second migration

```rb
  create_table "users", force: :cascade do |t|
    t.string "code", default: ""
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

which is the expected behavior. This is on 6.1.1. If you can get that version running let me know if the migration works.

**Comment by Piioo** [comment] 2021-05-21 06:12
I tested it with 6.1.1 and a new project and I still I do not have the default in schema.rb :(

Can it have something todo with the database version?

```docker
version: "2"
services:
  db:
    image: cockroachdb/cockroach:v20.1.8
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - database:/cockroach/cockroach-data
```

**Comment by Piioo** [comment] 2021-05-21 06:19
I have tested it now with version 6.1.1 on a new project and I have still the same problem :(

```diff
diff --git a/db/migrate/20210521061553_foo_name.rb b/db/migrate/20210521061553_foo_name.rb
new file mode 100644
index 0000000..c1aef42
--- /dev/null
+++ b/db/migrate/20210521061553_foo_name.rb
@@ -0,0 +1,5 @@
+class FooName < ActiveRecord::Migration[6.1]
+  def change
+    change_column :foo, :name, :string, default: ''
+  end
+end
diff --git a/db/schema.rb b/db/schema.rb
index 36c8218..950523b 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -10,7 +10,7 @@
 #
 # It's strongly recommended that you check this file into your version control system.

-ActiveRecord::Schema.define(version: 2021_05_21_060521) do
+ActiveRecord::Schema.define(version: 2021_05_21_061553) do

   create_table "bar", force: :cascade do |t|
     t.string "name"
(END)
```

Can it have something to do with the database version and docker?
```docker
version: "2"
services:
  db:
    image: cockroachdb/cockroach:v20.1.8
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - database:/cockroach/cockroach-data
```

I have no clue why this may be different.

**Comment by rafiss** [comment] 2021-05-21 06:28
@Piioo ah I see you are using CockroachDB 20.1.8. That version is pretty old, and I vaguely remember an issue similar to yours affecting v20.1.  Can you try using a newer version? See https://www.cockroachlabs.com/docs/releases/ We just had a new major version release of v21.1.0. Using the latest v20.2.10 release should work too.

**Comment by Piioo** [comment] 2021-05-21 08:24
I will try, but it will take some time (we need a few weeks to get the DB updated)

**Comment by rafiss** [comment] 2022-04-27 05:06
I will close this, but if you are able to reproduce this on a more recent version of CockroachDB please let me know.

**Closed by rafiss** 2022-04-27 05:06 UTC
